baseURL = "https://saejinheinert.com/"
title = "Saejin Mahlau-Heinert"
description = "Personal Website"

enableGitInfo = true

publishDir = "dist"

taxonomies = []

[params]
author = "Saejin Mahlau-Heinert"
css = "css/theme.css"
js = "js/theme.js"
VisibleSections = ["projects", "posts", "home"]

[markup.goldmark.renderer]
unsafe = true
