baseURL: "https://saejinmh.com/"
title: "Saejin Mahlau-Heinert"
description: "Personal Website"

googleAnalytics: "UA-125774774-1"
enableGitInfo: true

publishDir: "dist"

taxonomies: []

params:
  author: "Saejin Mahlau-Heinert"
  css: "css/theme.css"
  js: "js/theme.js"
